### ISSUE TITLE
Floats, not doubles?

### ISSUE THREAD

**Issue by sparr1** [MAPLE-Robot-Subgoaling/forklift#5]
Is there any reason all the doubles were converted to floats?

**Comment by khalil8500** [comment]
Since it uses gui, there are methods on paint which require the values to be floats. Instead of calculating everything with doubles and possibly losing the some significant figures, it is better to just do it in float instead of having to convert between the two every time we need to send everything to the visualizer.

**Comment by sparr1** [comment]
Actually, wouldn't it make sense for the visualizer to lose precision in reference to the actual code? It would be better for the AI (visualizer-less) to interact with the more precise doubles, whereas the visualizer's precision matters a great deal less to us.
